apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: mlplatform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: prometheus-data
          mountPath: /prometheus
  volumes:
  - name: prometheus-config
    configMap:
      name: prometheus-config
  - name: prometheus-data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: mlplatform
spec:
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: mlplatform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources/default.yaml
          subPath: default.yaml
        - name: grafana-dashboards
          mountPath: /etc/grafana/provisioning/dashboards/default.yaml
          subPath: default.yaml
        - name: grafana-dashboard
          mountPath: /var/lib/grafana/dashboards
  volumes:
  - name: grafana-datasources
    configMap:
      name: grafana-datasources
  - name: grafana-dashboards
    configMap:
      name: grafana-dashboards
  - name: grafana-dashboard
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: mlplatform
spec:
  selector:
    app: grafana
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: mlplatform
data:
  prometheus.yml: |
    # Your prometheus configuration here
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
      - static_configs:
        - targets: []
        scheme: http
        timeout: 10s
        api_version: v1
    scrape_configs:
    - job_name: prometheus-model-registry
      honor_timestamps: true
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets:
        - model-registry
    - job_name: prometheus-inference-server
      honor_timestamps: true
      scrape_interval: 15s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      static_configs:
      - targets:
        - inference-server

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: mlplatform
data:
  default.yaml: |
    # Your grafana datasources configuration here
    apiVersion: 1

    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus:9090 
      isDefault: true
      access: proxy
      editable: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: mlplatform
data:
  default.yaml: |
    # Your grafana dashboards configuration here

